### ISSUE TITLE
Bug: second overload of particleHandle.split() (with direction parameter) sometimes places particles wrong distance apart

### ISSUE THREAD

**Issue by sminsuk** [tissue-forge/tissue-forge#52] opened 2023-12-27 11:06 UTC
This occurs particularly when the provided direction vector is roughly parallel to the x axis (components y and z << x). I sent you 2 emails with details of my results and testing.

**Comment by tjsego** [comment] 2024-01-03 20:18
Can you provide a minimal example that reproduces this? I tried the following and detected no issues:

```
import tissue_forge as tf
import random


class ParentType(tf.ParticleTypeSpec):
    radius = 0.1


class ChildType(ParentType):
    pass


tf.init(dim=[10., 10., 10.])

type_parent = ParentType.get()
type_child = ChildType.get()

num_tests = 10000
noise_cf = 0.01
results = []
for _ in range(num_tests):
    p = type_parent()
    c = p.split(tf.FVector3(1, random.random() * noise_cf, random.random() * noise_cf))
    c.become(type_child)
    results.append(abs(c.relativePosition(p.position).length() - (p.radius + c.radius)) / (p.radius + c.radius))

print(max(results))

tf.show()
```

**Comment by sminsuk** [comment] 2024-01-03 23:48
Hmm. I will think about it and see what I can come up with. Thanks.

Sharon

**Comment by sminsuk** [comment] 2024-01-04 02:05
Okay. I ran your code. Then I tried making the x coordinate of your vector larger - for example:

`c = p.split(tf.FVector3(10, random.random() * noise_cf, random.random() * noise_cf))`

(note 10 instead of 1)
and immediately got much larger values for the output. (With x=10, I get an output of around 9 every time.)

Also, if I print `min(results)` along with `max(results)` (or even `sorted(results)`) I see that _**all**_ 10000 iterations of the loop produced a value around 9.

If you then set num_tests to 10 instead of 10000 and run it, you can see in the viewer that the particles are definitely not pairs of adjacent particles.

In my email I asked you whether the vector needs to be a unit vector. Clearly the one in your example is not, although it's not far off. Is there some other restriction on the vector? I would assume the vector is only being used for its direction, and its length would be ignored. True/False?

I checked the docs for split(), again. No mention of any such effect. Simply, "the parent and child particles are randomly placed exactly in contact". Oh, by the way, the description under Notes doesn't even mention the 2nd overload. It probably should.

**Comment by sminsuk** [comment] 2024-01-04 02:12
I also changed your example to make the vector point in the y or z direction, instead of x. Surprisingly, I got the same result. That does not match what I saw in my epiboly simulation.

**Comment by sminsuk** [comment] 2024-01-04 07:33
Came back and tried it with a _**shorter**_ vector -- changed your 1 to 0.1. The parent/daughter pairs come out overlapping! It's as if I were using the vector to specify the distance. I guess using a unit vector will likely solve the issue for me.

**Comment by tjsego** [comment] 2024-01-04 15:22
I'm unable to reproduce any of these observations from the described variations on windows, osx or ubuntu with the current develop branch. Can you share _exactly_ what code you ran along with a screenshot showing the errors you see?

**Comment by sminsuk** [comment] 2024-01-04 18:21
Wow, really? Okay. Here is a screenshot of PyCharm showing both the code and the text output (plus here's the code in text form too, in case you need to copy/paste for whatever reason), identical to yours except where the three comments call out my changes; and a screenshot of the rendered particles. 

You said you ran "with the current develop branch"; but I am running Tissue Forge version 0.2.0. Maybe that matters. And for the record I am running python 3.10, in PyCharm 2022.3.3, in macOS 12.6.5 Monterey.

Can you comment on whether split() expects a unit vector? I have tried it in my simulation now, and preliminary results suggest that it fixed the problem.

```
import tissue_forge as tf
import random


class ParentType(tf.ParticleTypeSpec):
    radius = 0.1


class ChildType(ParentType):
    pass


tf.init(dim=[10., 10., 10.])

type_parent = ParentType.get()
type_child = ChildType.get()

num_tests = 10      # <--- Changed
noise_cf = 0.01
results = []
for _ in range(num_tests):
    p = type_parent()
    c = p.split(tf.FVector3(10, random.random() * noise_cf, random.random() * noise_cf))     # <--- Changed
    c.become(type_child)
    results.append(abs(c.relativePosition(p.position).length() - (p.radius + c.radius)) / (p.radius + c.radius))

print(sorted(results))  # <--- Added
print(max(results))

tf.show()
```
<img width="1190" alt="Screen Shot 2024-01-04 at 9 57 50 AM" src="https://github.com/tissue-forge/tissue-forge/assets/3751590/b7664c8f-fc9d-47cb-bcb3-dcc301d2162b">
<img width="800" alt="Screen Shot 2024-01-04 at 9 57 19 AM" src="https://github.com/tissue-forge/tissue-forge/assets/3751590/38fc9ee5-da46-4ac2-9549-4b9954dac924">

**Comment by tjsego** [comment] 2024-01-04 19:27
Your installation version is the issue. The new overloads aren't yet in a release.

**Comment by sminsuk** [comment] 2024-01-04 20:09
0.2.0 DOES have an overload, and like I said in my email, I was using and reporting a bug in v 0.2.0. (Sorry not to have restated that on this page.) And I thought that was important to report because the bug could have carried over to the as yet unreleased implementation. I assumed you'd test it in the existing release. Are you saying this is a known issue / expected behavior?

**Comment by tjsego** [comment] 2024-01-04 20:31
I see. Yes, v0.2.0 expects a unit direction vector. This expectation will be removed in the next release.

**Comment by sminsuk** [comment] 2024-01-04 21:21
Ah, okay then. At last we're on the same page.

Making it a unit vector would have been an easy thing to try, and I even thought of it while implementing. But the doc didn't mention any such requirement, and given the existing description of the functionality, I thought it so unlikely to be the case that it didn't seem worth trying!

**Comment by tjsego** [comment] 2024-01-05 12:55
Anything else to address here, or can we close this?

**Comment by sminsuk** [comment] 2024-01-07 05:56
Close it. Looking forward to seeing the documentation for the enhanced version of this feature in your next release.

**Closed** 2024-01-09 19:08 UTC
